GET http://localhost:5165/matches

###
GET http://localhost:5165/matches/511

###
POST http://localhost:5165/matches
Content-Type: application/json

{
  "homeTeamId": 1,
  "awayTeamId": 2,
  "matchDate": "2025-01-23",
  "round": "Round 1",
  "homeScore": 3,
  "awayScore": 0
}

###
PUT http://localhost:5165/matches/511
Content-Type: application/json

{
  "homeTeamId": 1,
  "awayTeamId": 2,
  "matchDate": "2025-01-23",
  "round": "Round 1",
  "homeScore": 3,
  "awayScore": 0
}

###
DELETE http://localhost:5165/matches/1

###
GET http://localhost:5165/matches/2025-01-23:2025-01-24

###
GET http://localhost:5165/matches/mostwins